openapi: 3.0.3
info:
  title: Rain
  description: Rain API's Documentation
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

tags:
  - name: Auth
    description: Authentication Endpoints
  - name: Users
    description: User Endpoints

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR..."

  /users/me:
    get:
      tags:
        - Users
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "60d0fe4f5311236168a109ca"
                  name:
                    type: string
                    example: John Doe
                  email:
                    type: string
                    example: john@example.com
        401:
          $ref: "#/components/responses/UnauthorizedError"
