openapi: 3.0.3
info:
  title: Greenpad
  description: Greenpad Api Documentation
  version: 1.0.0

servers:
  - url: http://localhost:8060
    description: Local server

tags:
  - name: Auth
    description: Auth
  - name: Users
    description: Users

paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      in: header
      scheme: bearer
      bearerFormat: JWT
  responses:
    Forbidden:
      summary: Forbidden
      type: object
      properties:
        statusCode:
          type: integer
          example: 403
        message:
          type: string
          examples:
            emailNotVerified:
              value: "Pending Email verification"
            notAllowed:
              value: "You don't have permission to access this endpoint"
        details:
          example: null
    BadRequest:
      summary: Bad Request (Api Payload validation failed)
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        message:
          type: string
          example: Validation Failed
        details:
          type: array
          items:
            type: object
            properties:
              "{payload_field}":
                type: string
                example: "{payload_field validation error message}"
    UserNotFound:
      summary: User not found
      type: object
      properties:
        statusCode:
          type: integer
          example: 404
        message:
          type: string
          example: User not found
        details:
          type: string
          example: null
    UnAuthorized:
      summary: UnAuthorized
      type: object
      properties:
        statusCode:
          type: integer
          example: 401
        message:
          type: string
          example: Jwt expired/invalid
        details:
          example: null
    ServerError:
      summary: Internal Server Error
      type: object
      properties:
        statusCode:
          type: integer
          example: 500
        message:
          type: string
          example: Something went wrong
        details:
          example: nul
